### ISSUE TITLE
RFC 138: Add builder to project descriptor

### ISSUE THREAD

**Issue by dfreilich** [buildpacks/pack#1114]
Implement https://github.com/buildpacks/rfcs/pull/138 

# Summary
Add a `builder` key to the `project.toml` file, under `build`

Since a builder can be selected multiple ways, the following defines the order of precedence when selecting a builder:

1. `--builder` flag (highest precedence)
2. `project.toml` → `uild.builder`
3. configured builder (set via pack config default-builder)

## project.toml spec
```toml
[project]
id = "<string>"

[build]
builder = "<string>" # optional
```
