### ISSUE TITLE
Add a `--force-color` or env var equivalent to `pack build`

### ISSUE THREAD

**Issue by schneems** [buildpacks/pack#1839]
### Description

I wanted to emit the build output of my buildpack on every PR so I added it to my GitHub Actions. This works, but doesn't emit color because GH is not a TTY so this check fails https://github.com/buildpacks/pack/blob/cc6b0013f32d57bc01462e7cba7783fd6530ee23/internal/term/term.go#L13 and colors are supressed. Other tools introduce env vars such as `export CARGO_TERM_COLOR=always` or flags like `--force-color`. 

### Proposed solution

I see that there is a `pack build --no-color` I would like `pack build --force-color` to force color even when the output is not a TTY.

### Describe alternatives you've considered

As a workaround anyone who wants to do this can use `script -e -c "<pack build command here>"` to trick pack into thinking it is running in a TTY. I've done that here: https://github.com/heroku/buildpacks-ruby/pull/155/commits/a8e6ec48ca0a8849fffc7d6338cddd17f486e9d7

Or here's a copy if the SHA changes: 

```
  pack-getting-started-output:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install musl-tools
        run: sudo apt-get install musl-tools --no-install-recommends
      - name: Update Rust toolchain
        run: rustup update
      - name: Install Rust linux-musl target
        run: rustup target add x86_64-unknown-linux-musl
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.1
      - name: Install Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.2.0
      - name: Pull builder image
        run: |
          docker pull "heroku/builder:22"
          docker pull "heroku/heroku:22-cnb"
      - name: Clone ruby getting started guide
        run: mkdir tmp; git clone https://github.com/heroku/ruby-getting-started tmp/ruby-getting-started
      - name: Install libcnb-cargo for `cargo libcnb package` command
        run: cargo install libcnb-cargo
      - name: Compile ruby buildpack
        run: cargo libcnb package
      - name: Getting started guide output
        run: | # Use `script -e -c` to pretend to be a TTY for pack terminal color support
          script -e -c "pack build my-image --builder heroku/builder:22 --buildpack heroku/nodejs-engine --buildpack target/buildpack/debug/heroku_ruby --path tmp/ruby-getting-started --pull-policy never"
```

### Additional context

There are other alternatives mentioned in this thread on GHA https://github.com/actions/runner/issues/241#issuecomment-577360161 about various env vars.
