### ISSUE TITLE
Version required in project.toml when group is specified by id

### ISSUE THREAD

**Issue by ipmb** [buildpacks/pack#1862]
### Summary

My understanding is that when a version isn't included on a buildpack group, the latest should be used. If I specify a `uri` it works as expected, but if I specify an `id` it does not.

---

##### Steps

1. Create a `project.toml` with the following contents:
    ```toml
    [_]
    schema-version = "0.2"
    id = "io.buildpacks.my-app"
    
    [[io.buildpacks.group]]
    id = "heroku/nodejs"
    ````
2. Run `pack build myimg -B heroku/builder:22`

##### Current behavior

Command exits with error:

```
ERROR: failed to build: Invalid buildpack defined in project descriptor
```

##### Expected behavior

Image builds successfully using latest `heroku/nodejs` buildpack. If I replace `id = "heroku/nodejs"` with `uri = "urn:cnb:builder:heroku/nodejs"` it works as expected.

It also works if I add `version = "1.1.2"` to the group.

---

##### pack info

```
Pack:
  Version:  0.29.0+git-95c8060.build-4209
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.15.2

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10

Config:
```

##### docker info

```yaml
Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 56
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.22GiB
 Name: ll-server
 ID: c9a8aa17-3d40-4ba9-96e3-560be2a1a73c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: ipmb
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
