### ISSUE TITLE
Update labeler workflow to use v5.0.0 format

### ISSUE THREAD

**Issue by jjbustamante** [buildpacks/pack#1999]
### Description
With the Pull Request [1997](https://github.com/buildpacks/pack/pull/1997) we set the [labeler](https://github.com/actions/labeler) action to use version 4, this fixes the broken pipeline at that moment. version 5 introduced some breaking changes so we need to update our workflow file to reflect those changes.

### Proposed solution
I did the following but I was able to test it. 

```yaml
# Rules defined here: https://github.com/actions/labeler
type/chore:
- changed-files:
    any-glob-to-any-file: ['*.md', '**/*.yml', 'acceptance/**/*', '.github/**/*', 'go.mod', 'go.sum']

type/enhancement:
- changed-files:
    any-glob-to-any-file: ['*.go', '**/*.go']
```

### Additional context
check the github-action [documentation](https://github.com/actions/labeler/tree/main#pull-request-labeler)
