### ISSUE TITLE
`pack buildpack new --targets` creates `buildpack.toml` with wrong field/table names for distro name/version

### ISSUE THREAD

**Issue by edmorley** [buildpacks/pack#2120]
### Summary
The `pack buildpack new` command has a `--targets` option that allows for pre-populating the `[[targets]]` table in the generated `buildpack.toml` file.

However, the command currently uses the wrong field and table names if a distro name/version is specified:
- `targets.distributions` (instead of `targets.distros`)
- `versions` of type array (instead of `version` of type string)

xref:
- https://github.com/buildpacks/spec/issues/401
- https://github.com/buildpacks/rfcs/pull/310

cc @natalieparellano 

---

##### Steps

1. `pack buildpack new testcase-targets-distros --api 0.10 --targets "linux/amd64:ubuntu@123"`
2. `cat testcase-targets-distros/buildpack.toml`

##### Current behavior

```toml
# ...
[[targets]]
  os = "linux"
  arch = "amd64"

  [[targets.distributions]]
    name = "ubuntu"
    versions = ["123"]
```

##### Expected behavior

```toml
# ...
[[targets]]
  os = "linux"
  arch = "amd64"

  [[targets.distros]]
    name = "ubuntu"
    version = "123"
```

---

### Environment

```
$ pack --version
0.33.2+git-f2cffc4.build-5562
```
