### ISSUE TITLE
Pack warns about valid `clear-env` key in `buildpack.toml`

### ISSUE THREAD

**Issue by edmorley** [buildpacks/pack#2253]
### Summary

Similar to #2192, Pack CLI gives an incorrect warning about a valid `buildpack.toml` key, but this time it's the `clear-env` key, which is allowed  in the spec:
https://github.com/buildpacks/spec/blob/main/buildpack.md#buildpacktoml-toml

---

##### Steps

1. Create a buildpack whose `buildpack.toml` contains:
    ```toml
    api = "0.11"
    
    [buildpack]
    id = "testing-buildpack"
    version = "0.0.0"
    clear-env = true
    ```
2. `pack build --builder heroku/builder:24 --buildpack <path_to_that_buildpack>`

##### Current behavior

```
Warning: Ignoring unexpected key(s) in descriptor for buildpack testing-buildpack: buildpack.clear-env
===> ANALYZING
...
```

##### Expected behavior

No warning about an unexpected `clear-env` key.

---

##### pack info
Pack CLI v0.35.1
lifecycle 0.20.1
