### ISSUE TITLE
Display error when no lifecycle descriptor is provided

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#267]
As part of RFCs [#10](https://github.com/buildpack/rfcs/blob/master/text/0010-api-versions.md) and [#11](https://github.com/buildpack/rfcs/blob/master/text/0011-lifecycle-descriptor.md), it is imperative that we have the lifecycle descriptor available to determine compatibility between lifecycle and provided buildpacks.

Relates to #260 

#### Fail when descriptor not found
**Given**  I have a lifecycle archive at path `/path/to/lifecycle.tgz` WITHOUT a `lifecycle.toml` file at the root of the archive
**When** I run `pack create-builder -b builder.toml` and the `lifecycle.uri` field in the`builder.toml` points to the given lifecycle
**Then** `pack` should fail with exit code not equal to 0
**And** `pack` should output `ERROR: provided lifecycle is missing lifecycle descriptor.`

**Comment by Zanadar** [comment]
Validated that creating a builder where the lifecycle bundle lack a `lifecycle.toml` fails.

```bash
± zm |master ✓| → tar -tvf out/bad-lifecycle-v0.0.0+linux.x86-64.tgz
drwxr-xr-x  0 pivotal staff       0 Jan 13 12:50 lifecycle/
-rwxr-xr-x  0 pivotal staff 8646656 Jan 13 12:50 lifecycle/launcher
-rwxr-xr-x  0 pivotal staff 10067968 Jan 13 12:50 lifecycle/rebaser
-rwxr-xr-x  0 pivotal staff  8835072 Jan 13 12:50 lifecycle/detector
-rwxr-xr-x  0 pivotal staff 10469376 Jan 13 12:50 lifecycle/exporter
-rwxr-xr-x  0 pivotal staff  8863744 Jan 13 12:50 lifecycle/builder
-rwxr-xr-x  0 pivotal staff 10412032 Jan 13 12:50 lifecycle/analyzer
-rwxr-xr-x  0 pivotal staff  9474048 Jan 13 12:50 lifecycle/restorer
```

```toml
[stack]
  id = "pack.test.stack"
  build-image = "pack-test/build"
  run-image = "pack-test/run"

# run-image-mirror and lifecycle are appended by acceptance tests
[lifecycle]
  uri = "/Users/pivotal/workspace/lifecycle/out/bad-lifecycle-v0.0.0+linux.x86-64.tgz"
```

```
± zm |master U:1 ✗| → ./out/pack create-builder test/pack/issues/267 --builder-config acceptance/testdata/pack_current/builder.toml
Warning: builder configuration: empty order definition
ERROR: fetch lifecycle: invalid lifecycle: could not find entry path 'lifecycle.toml': not exist
```
