### ISSUE TITLE
Pack export fails with: failed to export: previous image did not have layer with sha ''

### ISSUE THREAD

**Issue by josephlewis42** [buildpacks/pack#336]
I have a buildpack builder image that works locally via pack but fails when the lifecycle components are called in a remote pipeline. The error I'm seeing is the following during the export step:

```
Exporting layer 'app' with SHA sha256:eb95b8187adb5e960c872773e4f1c4880cfd51a464b421883f9afad845f3abc5
Exporting layer 'config' with SHA sha256:78e1da51ad817604babfeb24d453799758af7df1aa8daeb3292e52c71240cc08
Exporting layer 'launcher' with SHA sha256:ef2cd5869b4d3995edbba8144c8c448f864f3895ea264967701a9a97547d6087
Exporting layer 'org.cloudfoundry.openjdk:openjdk-jre' with SHA sha256:53458213bcc7428b157f62fd41524f2fa44e6808c091c333bb94d70436e5e23a
Reusing layer 'org.cloudfoundry.tomcat:catalina-base' with SHA 
Error: failed to export: previous image did not have layer with sha ''
```

## Steps to reproduce

Create a builder:

```
description = "Sample builder"

[[buildpacks]]
id = "org.cloudfoundry.archiveexpanding"
uri = "https://storage.googleapis.com/cnb-buildpacks/archive-expanding-cnb/org.cloudfoundry.archiveexpanding-1.0.51.tgz"

[[buildpacks]]
id = "org.cloudfoundry.openjdk"
uri = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.0.26.tgz"

[[buildpacks]]
id = "org.cloudfoundry.jvmapplication"
uri = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.0.41.tgz"

[[buildpacks]]
id = "org.cloudfoundry.tomcat"
uri = "https://storage.googleapis.com/cnb-buildpacks/tomcat-cnb/org.cloudfoundry.tomcat-1.0.66.tgz"

[[order]]
group = [
  ### Builders, order is meaningful
  { id = "org.cloudfoundry.archiveexpanding", optional = true },
  { id = "org.cloudfoundry.openjdk" },
  { id = "org.cloudfoundry.jvmapplication" },

  ### Runtimes, ordered by priority
  { id = "org.cloudfoundry.tomcat", optional = true },
]

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "gcr.io/kf-releases/run:latest"
build-image = "gcr.io/kf-releases/build:latest"
```

Create the builder:

```
pack create-builder --builder-config builder.toml  --publish gcr.io/kf-releases/bad-builder
```

Create a sample WAR file to try building:

```
git clone https://github.com/cloudfoundry/java-test-applications/tree/master/web-servlet-2-application
cd web-servlet-2-application
gradle build
cd build/libs
```

Build locally (this works):

```
$ pack build passlocal/passlocal --builder gcr.io/kf-releases/bad-builder
Pulling image gcr.io/kf-releases/bad-builder:latest

<snip>

===> EXPORTING
[exporter] Exporting layer 'app' with SHA sha256:8bf4e61b536076f534cc388c3e5994fbf0bd4f045b7a572c160fa6d435692fbd
[exporter] Exporting layer 'config' with SHA sha256:7a85156ee2192ccbd71bde9685da1d3b0c3049fb2907de0cce7f9634e3283127
[exporter] Exporting layer 'launcher' with SHA sha256:ef2cd5869b4d3995edbba8144c8c448f864f3895ea264967701a9a97547d6087
[exporter] Exporting layer 'org.cloudfoundry.openjdk:openjdk-jre' with SHA sha256:c01d3108656d9135fa72131e2e7be2122ff54d7684565aa8ef88682ade2a3781
[exporter] Exporting layer 'org.cloudfoundry.tomcat:catalina-base' with SHA sha256:d6ab8b4fc68c33e1ae484104e5dae7932e249a936ae66ad11f697d80e9943bca
[exporter] Exporting layer 'org.cloudfoundry.tomcat:tomcat' with SHA sha256:c6cf8118099562529f6503e3bd0c34a600485f1ffab01c7be7543c7348f53fe9
[exporter] *** Images:
[exporter]       index.docker.io/passlocal/passlocal:latest - succeeded
[exporter] 
[exporter] *** Image ID: 91a5513b55e78b7e1403ca12009b45cdb64edb0d808b781c2b36273f0958c788
===> CACHING
Successfully built image passlocal/passlocal
```

Try building remotely with a Knative Build pipeline, the build is the same but the export step fails:

```
Exporting layer 'app' with SHA sha256:eb95b8187adb5e960c872773e4f1c4880cfd51a464b421883f9afad845f3abc5
Exporting layer 'config' with SHA sha256:78e1da51ad817604babfeb24d453799758af7df1aa8daeb3292e52c71240cc08
Exporting layer 'launcher' with SHA sha256:ef2cd5869b4d3995edbba8144c8c448f864f3895ea264967701a9a97547d6087
Exporting layer 'org.cloudfoundry.openjdk:openjdk-jre' with SHA sha256:53458213bcc7428b157f62fd41524f2fa44e6808c091c333bb94d70436e5e23a
Reusing layer 'org.cloudfoundry.tomcat:catalina-base' with SHA 
Error: failed to export: previous image did not have layer with sha ''
```

The container that failed has the following setup:

```
- args:
  - -layers=/layers
  - -helpers=true
  - -app=/workspace
  - -image=
  - -group=/layers/group.toml
  - gcr.io/kf-source/app_joseph_badapp:0
  command:
  - /lifecycle/exporter
  env:
  - name: HOME
    value: /builder/home
  image: gcr.io/kf-releases/bad-builder
  imagePullPolicy: Always
  name: build-step-export
  resources: {}
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  volumeMounts:
  - mountPath: /layers
    name: empty-dir
  - mountPath: /workspace
    name: workspace
  - mountPath: /builder/home
    name: home
  - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    name: default-token-wlwh4
    readOnly: true
  workingDir: /workspace
```

Versions:

```
$ pack version
v0.4.1 (git sha: 90e88e7b1dc02ca65e22548fdfbeabec4c9879a6)

$ pack inspect-builder gcr.io/kf-releases/bad-builder
Inspecting builder: gcr.io/kf-releases/bad-builder

Remote
------

Description: Sample failing builder

Stack: io.buildpacks.stacks.bionic

Lifecycle:
  Version: 0.4.0
  Buildpack API: 0.2
  Platform API: 0.1
<snip>
```
