### ISSUE TITLE
Adding a meta-buildpack via `--buildpack` does not resolve builder buildpacks

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#352]
### Motivation
As a user, I'd like to be able to provide a _meta-buildpack_ with a custom order. This custom order would reference buildpacks originally the builder.

### Reproduction
1. Create buildpack.toml with contents:
```toml
api = "0.2"

[buildpack]
id      = "com.example"
name    = "Example Java Buildpack"
version = "0.0.1"

[[order]]
group = [

### Order is strictly enforced
  { id = "org.cloudfoundry.openjdk",                   version = "v1.0.29" },
  { id = "org.cloudfoundry.jvmapplication",            version = "1.0.43" },

### Order determines precedence
  { id = "org.cloudfoundry.springboot",                version = "1.0.55", optional = true },
]
```
2. Build an app using the following command:
```bash
pack build d-app --builder index.docker.io/cloudfoundry/cnb:bionic --buildpack . --path ~/dev/samples/apps/java-maven/
```

**Result**
```bash
Pulling image index.docker.io/cloudfoundry/cnb:bionic
bionic: Pulling from cloudfoundry/cnb
Digest: sha256:488ab14ea61d6e0210fb624308a56e67e22792a79769335e1205e5e9c5cb57ed
Status: Image is up to date for cloudfoundry/cnb:bionic
Selected run image cloudfoundry/run:base-cnb
Pulling image cloudfoundry/run:base-cnb
base-cnb: Pulling from cloudfoundry/run
Digest: sha256:bd9df33bff1644d567a8f74b40b2f73246325b665ae9beeef3bea7e7fa2dd3ff
Status: Image is up to date for cloudfoundry/run:base-cnb
fetching buildpack from .
adding buildpack com.example version 0.0.1 to builder
setting custom order
ERROR: validating buildpacks: buildpack org.cloudfoundry.openjdk@v1.0.29 not found on the builder
```

**Expected**

Successful building of app
