### ISSUE TITLE
`pack inspect-image --bom` should output the Bill of Materials (BOM) in a human-friendly format

### ISSUE THREAD

**Issue by alexbrand** [buildpacks/pack#378]
Currently, the `pack inspect-image --bom` command dumps the BOM as a JSON blob:

![image](https://user-images.githubusercontent.com/545723/68482478-b00ead80-0207-11ea-8aac-877a7f8ba128.png)

The JSON blob is great for passing the BOM to another utility, but it is difficult to parse as a human. I am wondering if there's an improvement we can make here.

**Comment by ekcasey** [comment]
@alexbrand The simplest thing we could do is expand the JSON to make it more easier scan through. Because the metadata can contain arbitrarily nested keys and values the entire BOM is hard to print in a tabular or friendly format.

We could print just the name, version and contributing buildpack from each item in a table if that was useful to users.

**Comment by jromero** [comment]
Do you have any suggestion?

BOM is an arbitrary dataset. Without making any assumptions I wonder if it's easy enough to provide the BOM output in other formats such as YAML. Would that satisfy this request?

Example output using `yj`:

```shell
./out/pack inspect-image jromeropivot/spring-music:dev --bom | yj -jy
```

```yaml
local:
- buildpack:
    id: org.cloudfoundry.openjdk
    version: 1.0.0-RC03
  metadata:
    licenses:
    - type: GPL-2.0 WITH Classpath-exception-2.0
      uri: https://openjdk.java.net/legal/gplv2+ce.html
    name: OpenJDK JDK
    sha256: 90c33cf3f2ed0bd773f648815de7347e69cfbb3416ef3bf41616ab1c4aa0f5a8
    stacks:
    - io.buildpacks.stacks.bionic
    - org.cloudfoundry.stacks.cflinuxfs3
    uri: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.4%!B(MISSING)11/OpenJDK11U-jdk_x64_linux_hotspot_11.0.4_11.tar.gz
  name: openjdk-jdk
  version: 11.0.4
...
```
