### ISSUE TITLE
pack create-builder should de-dup buildpacks list

### ISSUE THREAD

**Issue by kvedurmu** [buildpacks/pack#430]
We recently ran into issues creating a builder packaged with CNBs that reference the same dependency. Here's a snippet of our builder.toml that is causing this issue:

```
[[buildpacks]]
id = "org.cloudfoundry.node-engine"
uri = "/tmp/build/59a8880f/sources/dotnet-core-cnb/org.cloudfoundry.node-engine"

[[buildpacks]]
id = "org.cloudfoundry.node-engine"
uri = "/tmp/build/59a8880f/sources/nodejs-cnb/org.cloudfoundry.node-engine"
```

When we ran `pack create-builder localhost:5000/cloudfoundry/cnb:bionic --builder-config builder.toml --publish` we see the following error:

```
ERROR: failed to register layer: Error processing tar file(duplicates of file paths not supported): 
```

**Expected Behavior**
- If a builder toml has multiple entries with the same id that both reference the same version of a CNB, pack should de-dup these entries, and `pack create-builder` succeeds
- If a builder.toml has multiple entries with the same id that both reference different versions of the CNB, pack adds both versions separately

**Comment by Zanadar** [comment]
FYI
```
root@45fa57ec-7290-4959-619c-6c1af8ba6ada:/tmp/build/59a8880f# ./pack-cli/pack report
Pack:
  Version:  v0.6.0 (git sha: 109b629d388cec0ed3836b9fed6717727a9187c1)
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.5.0

Config:
(error: open /root/.pack/config.toml: no such file or directory)
```

**Comment by dfreilich** [comment]
What made this more confusing is that the versions of the dup'd cnb were different. One of the order's (.NET Core, [here](https://github.com/cloudfoundry/dotnet-core-cnb/blob/753e711c842089415039b6d358b0e0d4960573ce/buildpack.toml#L79)) had `node-engine-cnb` `v0.0.124`, while another (Nodejs CNB, [here](https://github.com/cloudfoundry/nodejs-cnb/blob/769129cb2c907ff330e6f904f80ea8373ef58261/buildpack.toml#L51)) had `node-engine-cnb` `v0.0.125`. 

Shouldn't that make the layers different, and therefore not be duplicates of file paths?

**Comment by jromero** [comment]
@dfreilich yes it should. We should really look into that.

**Comment by ameyer-pivotal** [comment]
@kvedurmu Can you show the full toml for your builder? I'm curious to see what the `order` looks like.

**Comment by ameyer-pivotal** [comment]
I'm able to reproduce a similar but not exact error with the following builder.toml:

```toml
[[buildpacks]]
uri = "noop-buildpack"

[[buildpacks]]
uri = "noop-buildpack2"

[[order]]
[[order.group]]
  id = "noop.buildpack"
  version = "noop.buildpack.version"

[[order.group]]
  id = "noop.buildpack"
  version = "noop.buildpack.version.2"
  
[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "cloudfoundry/build:base-cnb"
  run-image = "cloudfoundry/run:base-cnb"
```

Output:
```
$ pack create-builder bldr -b sandbox/builder.toml
base-cnb: Pulling from cloudfoundry/build
Digest: sha256:b30b850f5b4d2e11313f0ec152952eace285ce7a3bc203ca5cdcfa8e5bb232a6
Status: Image is up to date for cloudfoundry/build:base-cnb
ERROR: failed to write image to the following tags: [bldr: save image 'bldr': Error: No such image: eeb277220e9b985e1365abeb7375e3194d17d779d83a730c8eb42af8a82b49b4]
```

Note that the second buildpack also has a different version, which shouldn't cause any problems...

**Comment by ameyer-pivotal** [comment]
If I adjust both buildpacks to be identical (same ID and version), then I get the same error, but with an expected warning:

```
Warning: buildpack noop.buildpack@noop.buildpack.version already exists on builder and will be overwritten
ERROR: failed to write image to the following tags: [bldr: save image 'bldr': Error: No such image: 75be73f6dc54440e45d25b6ade8c96194e868419ff3e09dc3979af6cfe709819]
```

**Comment by mdelillo** [comment]
We generate the builder.toml in a concourse job so all of the buildpack URIs are local paths, but here it is:

```toml
description = "Ubuntu bionic base image with buildpacks for Java, NodeJS and Golang"

[[buildpacks]]
id = "org.cloudfoundry.buildsystem"
uri = "/tmp/build/59a8880f/sources/buildsystem-cnb/org.cloudfoundry.buildsystem"

[[buildpacks]]
id = "org.cloudfoundry.go"
uri = "/tmp/build/59a8880f/sources/go-cnb/org.cloudfoundry.go"

[[buildpacks]]
id = "org.cloudfoundry.archiveexpanding"
uri = "/tmp/build/59a8880f/sources/archiveexpanding-cnb/org.cloudfoundry.archiveexpanding"

[[buildpacks]]
id = "org.cloudfoundry.springautoreconfiguration"
uri = "/tmp/build/59a8880f/sources/springautoreconfiguration-cnb/org.cloudfoundry.springautoreconfiguration"

[[buildpacks]]
id = "org.cloudfoundry.debug"
uri = "/tmp/build/59a8880f/sources/debug-cnb/org.cloudfoundry.debug"

[[buildpacks]]
id = "org.cloudfoundry.nodejs"
uri = "/tmp/build/59a8880f/sources/nodejs-cnb/org.cloudfoundry.nodejs"

[[buildpacks]]
id = "org.cloudfoundry.openjdk"
uri = "/tmp/build/59a8880f/sources/openjdk-cnb/org.cloudfoundry.openjdk"

[[buildpacks]]
id = "org.cloudfoundry.jvmapplication"
uri = "/tmp/build/59a8880f/sources/jvmapplication-cnb/org.cloudfoundry.jvmapplication"

[[buildpacks]]
id = "org.cloudfoundry.springboot"
uri = "/tmp/build/59a8880f/sources/springboot-cnb/org.cloudfoundry.springboot"

[[buildpacks]]
id = "org.cloudfoundry.procfile"
uri = "/tmp/build/59a8880f/sources/procfile-cnb/org.cloudfoundry.procfile"

[[buildpacks]]
id = "org.cloudfoundry.googlestackdriver"
uri = "/tmp/build/59a8880f/sources/googlestackdriver-cnb/org.cloudfoundry.googlestackdriver"

[[buildpacks]]
id = "org.cloudfoundry.jdbc"
uri = "/tmp/build/59a8880f/sources/jdbc-cnb/org.cloudfoundry.jdbc"

[[buildpacks]]
id = "org.cloudfoundry.dotnet-core"
uri = "/tmp/build/59a8880f/sources/dotnet-core-cnb/org.cloudfoundry.dotnet-core"

[[buildpacks]]
id = "org.cloudfoundry.jmx"
uri = "/tmp/build/59a8880f/sources/jmx-cnb/org.cloudfoundry.jmx"

[[buildpacks]]
id = "org.cloudfoundry.azureapplicationinsights"
uri = "/tmp/build/59a8880f/sources/azureapplicationinsights-cnb/org.cloudfoundry.azureapplicationinsights"

[[buildpacks]]
id = "org.cloudfoundry.tomcat"
uri = "/tmp/build/59a8880f/sources/tomcat-cnb/org.cloudfoundry.tomcat"

[[buildpacks]]
id = "org.cloudfoundry.distzip"
uri = "/tmp/build/59a8880f/sources/distzip-cnb/org.cloudfoundry.distzip"

[[buildpacks]]
id = "org.cloudfoundry.dep"
uri = "/tmp/build/59a8880f/sources/go-cnb/org.cloudfoundry.dep"

[[buildpacks]]
id = "org.cloudfoundry.go-compiler"
uri = "/tmp/build/59a8880f/sources/go-cnb/org.cloudfoundry.go-compiler"

[[buildpacks]]
id = "org.cloudfoundry.go-mod"
uri = "/tmp/build/59a8880f/sources/go-cnb/org.cloudfoundry.go-mod"

[[buildpacks]]
id = "org.cloudfoundry.node-engine"
uri = "/tmp/build/59a8880f/sources/nodejs-cnb/org.cloudfoundry.node-engine"

[[buildpacks]]
id = "org.cloudfoundry.nodejs-compat"
uri = "/tmp/build/59a8880f/sources/nodejs-cnb/org.cloudfoundry.nodejs-compat"

[[buildpacks]]
id = "org.cloudfoundry.npm"
uri = "/tmp/build/59a8880f/sources/nodejs-cnb/org.cloudfoundry.npm"

[[buildpacks]]
id = "org.cloudfoundry.yarn"
uri = "/tmp/build/59a8880f/sources/nodejs-cnb/org.cloudfoundry.yarn"

[[buildpacks]]
id = "org.cloudfoundry.dotnet-core-aspnet"
uri = "/tmp/build/59a8880f/sources/dotnet-core-cnb/org.cloudfoundry.dotnet-core-aspnet"

[[buildpacks]]
id = "org.cloudfoundry.dotnet-core-build"
uri = "/tmp/build/59a8880f/sources/dotnet-core-cnb/org.cloudfoundry.dotnet-core-build"

[[buildpacks]]
id = "org.cloudfoundry.dotnet-core-conf"
uri = "/tmp/build/59a8880f/sources/dotnet-core-cnb/org.cloudfoundry.dotnet-core-conf"

[[buildpacks]]
id = "org.cloudfoundry.dotnet-core-runtime"
uri = "/tmp/build/59a8880f/sources/dotnet-core-cnb/org.cloudfoundry.dotnet-core-runtime"

[[buildpacks]]
id = "org.cloudfoundry.dotnet-core-sdk"
uri = "/tmp/build/59a8880f/sources/dotnet-core-cnb/org.cloudfoundry.dotnet-core-sdk"

[[buildpacks]]
id = "org.cloudfoundry.icu"
uri = "/tmp/build/59a8880f/sources/dotnet-core-cnb/org.cloudfoundry.icu"

[[buildpacks]]
id = "org.cloudfoundry.node-engine"
uri = "/tmp/build/59a8880f/sources/dotnet-core-cnb/org.cloudfoundry.node-engine"

[lifecycle]
version = "0.5.0"

[[order]]

[[order.group]]
id = "org.cloudfoundry.openjdk"

[[order.group]]
id = "org.cloudfoundry.buildsystem"
optional = true

[[order.group]]
id = "org.cloudfoundry.jvmapplication"

[[order.group]]
id = "org.cloudfoundry.tomcat"
optional = true

[[order.group]]
id = "org.cloudfoundry.springboot"
optional = true

[[order.group]]
id = "org.cloudfoundry.distzip"
optional = true

[[order.group]]
id = "org.cloudfoundry.procfile"
optional = true

[[order.group]]
id = "org.cloudfoundry.azureapplicationinsights"
optional = true

[[order.group]]
id = "org.cloudfoundry.debug"
optional = true

[[order.group]]
id = "org.cloudfoundry.googlestackdriver"
optional = true

[[order.group]]
id = "org.cloudfoundry.jdbc"
optional = true

[[order.group]]
id = "org.cloudfoundry.jmx"
optional = true

[[order.group]]
id = "org.cloudfoundry.springautoreconfiguration"
optional = true

[[order]]

[[order.group]]
id = "org.cloudfoundry.nodejs"

[[order]]

[[order.group]]
id = "org.cloudfoundry.go"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core"

[stack]
build-image = "cloudfoundry/build:base-cnb"
id = "io.buildpacks.stacks.bionic"
run-image = "cloudfoundry/run:base-cnb"
```
