### ISSUE TITLE
Validate buildpackages

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#441]
## Description
1. For correctness, a `buildpackage` is a packaged buildpack and it’s dependendencies (which can be other buildpacks). We should validate that the buildpackage does not contain arbitrary buildpacks and is therefore correct.
2. For assurance, we want to make sure all the dependencies are present in a package.

### AC1. Extraneous buildpack
> `pack create-package` of a `buildpackage` that contains a `buildpack` not specified in its configuration should fail.

**Given** buildpack A at `./buildpack.A/` has `buildpack.toml`:
```toml
api = "0.2"

[buildpack]
id = "buildpack.A"
version = "0.0.1"

[[stacks]]
id = "some.stack"
```
**And** buildpack B at `./buildpack.B/` has `buildpack.toml`:
```toml
api = "0.2"

[buildpack]
id = "buildpack.B"
version = "0.0.1"

[[stacks]]
id = "some.stack"
```
**When** I run `pack create-package` with `package.toml`:
```toml
[buildpack]
uri = "./buildpack.A/"

[[dependencies]]
uri = "./buildpack.B/"
```
**Then** operation should fail with exit code not equal to 0
**And** the following error should be displayed:
```
ERROR: buildpack 'buildpack.B@0.0.1' is not used by buildpack `buildpack.A@0.0.1`.
```

### AC2. Missing buildpack
> `pack create-package` of a `buildpackage` that lacks buildpacks contained in its configuration should fail.

**Given** buildpack A at `./buildpack.A/` has `buildpack.toml`:
```toml
api = "0.2"

[buildpack]
id = "buildpack.A"
version = "0.0.1"

[[order]]
[[order.group]]
id = "buildpack.B"
version = "0.0.1"
```
**When** I run `pack create-package` with `package.toml`:
```toml
[buildpack]
uri = "./buildpack.A/"
```
**Then** operation should fail with exit code not equal to 0
**And** the following error should be displayed:
```
ERROR: buildpack 'buildpack.A@0.0.1' references buildpack `buildpack.B@0.0.1` which is not present.
```

### Additional context
https://github.com/buildpacks/spec/blob/master/distribution.md
