### ISSUE TITLE
Validate contents of package.toml

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#456]
### Description
`pack` should validate `package.toml` during buildpackage creation

#### AC1. Tables

**Given** `package.toml` contains an array of tables that is not expected:
```toml
[buildpack]
uri = "noop-buildpack.tgz"

[[dependenceis]] # Notice: this is misspelled
image = "some/package-dep"
```
**When** I run `pack create-package some/package --package-config package.toml`
**Then** it should error with the following message:
```
Unknown configuration element 'dependenceis' in 'package.toml'
```

#### AC2. Keys

**Given** `package.toml` contains  is not expected:
```toml
[buildpack]
# Notice: this should be `uri`
url = "noop-buildpack.tgz"

[[dependencies]]
image = "some/package-dep"
```
**When** I run `pack create-package some/package --package-config package.toml`
**Then** it should error with the following message:
```
Unknown configuration element 'url' in 'package.toml'
```
