### ISSUE TITLE
Bump DefaultLifecycle to 0.6.0

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#465]
Upon release of [lifecycle 0.6.0](https://github.com/buildpacks/lifecycle/milestone/8) we would want to bump pack's DefaultLifecycle to 0.6.0.

#### AC 1. Report
When I run `pack report`
Then I see `Default Lifecycle Version:  0.6.0`

#### AC 2. Create Builder
Given I have `builder.toml`:
```toml
[stack]
id = "io.buildpacks.samples.stacks.alpine"
run-image = "cnbs/sample-stack-run:alpine"
build-image = "cnbs/sample-stack-build:alpine"
```
And I create a builder via `pack create-builder my-builder --builder-config builder.toml`
When I run `pack inspect-builder my-builder`
Then I should see the following:
```
...

Lifecycle:
  Version: 0.6.0
  Buildpack API: 0.2
  Platform API: 0.2

...
```
