### ISSUE TITLE
builder.toml: Replace packages with buildpacks

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#503]
### Description
In order to have alignment of use for packaged buildpacks the `builder.toml` should be updated to follow the same semantics as `package.toml`.

### Proposed solution
Replace the following declaration:

```toml
[[packages]]
id = "..."
version = "..."
image = "..."
```

with:

```toml
[[buildpacks]] # <--- notice the use of existing array table `buildpacks`
id = "..."
version = "..."
image = "..."
```

### Additional considerations

* Docs should be updated accordingly. (https://github.com/buildpacks/docs/pull/121)
