### ISSUE TITLE
Implement Service Bindings extension

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#504]
## Summary

Implement service [binding spec](https://github.com/buildpacks/spec/blob/master/extensions/bindings.md) relevant to `pack`:
https://github.com/buildpacks/spec/blob/master/extensions/bindings.md#detect-and-build-phases

### Basic Usage

**Given** the following `<bindings-config>.toml` file:
```toml
[alpha]
[alpha.metadata]
kind = "alpha-kind"
provider = "alpha-provider"
tags = ["alpha-tag-1", "alpha-tag-2"]
other-key = 4
[alpha.secrets]
secret-key = "secret-value"

[bravo]
[bravo.metadata]
kind = "bravo-kind"
provider = "bravo-provider"
tags = ["bravo-tag-1", "bravo-tag-2"]
other-key = "bravo-other-key"
```
**When** the following command is executed:
`pack build --bindings-config <bindings-config>.toml`
**Then** `pack` should mount the following file structure into the `detect` and `build` phases of lifecycle execution. The contents of the leaf node files should be the contents of the corresponding keys in the `<bindings-config>.toml`:

```bash
/platform/bindings
├── alpha
│   ├── metadata
│   │   ├── kind
│   │   ├── other-key
│   │   ├── provider
│   │   └── tags
│   └── secret
│       └── secret-key
└── bravo
    └── metadata
        ├── kind
        ├── other-key
        ├── provider
        └── tags
```

### Help

**When** the following command is executed:
```shell
pack build --help
```
**Then** the following should be displayed under "Flags":
```
--bindings-config string            Path to bindings TOML file
```
