### ISSUE TITLE
Validate contents of builder.toml

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#510]
While working on https://github.com/buildpacks/pack/issues/503 we found that `builder.toml` is not being validated like `package.toml`. We should validate `builder.toml`.

### Description
`pack` should validate `builder.toml` during builder creation

#### AC1. Tables

**Given** `builder.toml` contains an array of tables that is not expected:
```toml
[[buildpacks]]
uri = "noop-buildpack.tgz"

[[ordre]] # Notice: this is misspelled
    [[order.group]]
    id = "some-buildpack-id"
    version = "some-buildpack-version"
```
**When** I run `pack create-builder builder-image --builder-config builder.toml`
**Then** it should error with the following message:
```
Unknown configuration element 'ordre' in 'builder.toml'
```

#### AC2. Keys

**Given** `builder.toml` contains a key that is not expected:
```toml
[[buildpacks]]
# Notice: this should be `uri`
url = "noop-buildpack.tgz"

[[buildpacks]]
image = "some/package-dep"
```
**When** I run `pack create-builder builder-image --builder-config builder.toml`
**Then** it should error with the following message:
```
Unknown configuration element 'url' in 'builder.toml'
```
